openapi: 3.0.4

info:
  title: Bikeo - Bike Rental Platform
  version: 0.0.1

paths:
  /api/user/me:
    get:
      tags:
        - User
      summary: Retrieve the current user's information
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  ssoId:
                    type: string
                    format: uuid
                    description: Unique identifier of the user
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                  firstName:
                    type: string
                  lastName:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
                      enum: [ 'ROLE_CYCLIST', 'ROLE_ADMIN' ]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
