openapi: 3.0.4
info:
  title: API
  version: X.X.X

paths:
  /api/menu-item:
    get:
      parameters:
        - name: currentPage
          in: query
          schema:
            type: integer
        - name: pageSize
          in: query
          schema:
            type: integer
      tags:
        - Restaurant
      summary: Menu item collection
      responses:
        "200":
          description: Collection returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemCollection'
    post:
      tags:
        - Restaurant
      summary: Create menu item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: object
                  properties:
                    net:
                      type: integer
                      description: value in cents
                    vat:
                      type: integer
                      description: value in basis points e.g. 8050 = 8.5%
      responses:
        "201":
          description: Resource created
  /api/menu-item/{id}:
    put:
      tags:
        - Restaurant
      summary: Updates menu item
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: object
                  properties:
                    net:
                      type: integer
                      description: value in cents
                    vat:
                      type: integer
                      description: value in basis points e.g. 8050 = 8.5%
      responses:
        "204":
          description: Resource updated
components:
  schemas:
    MenuItemCollectionElement:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        priceGross:
          type: integer
          description: Gross price in cents
    MenuItemCollection:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/MenuItemCollectionElement'
        - $ref: '#/components/schemas/PaginationResult'

    PaginationResult:
      type: object
      properties:
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
              example: 1
              default: 1
            pageSize:
              type: integer
              example: 10
              default: 10
            totalItems:
              type: integer
