framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
when@test:
    framework:
        cache:
            app: cache.adapter.null
            system: cache.adapter.null
            default_redis_provider: null
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.adapter.null
                doctrine.system_cache_pool:
                    adapter: cache.adapter.null
