doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        server_version: '17.0'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            s__user__user_id: App\Shared\Infrastructure\DAL\Mapping\User\UserIdType
            s-vat_rate: App\Shared\Infrastructure\DAL\Mapping\VatRateType
            s__money: App\Shared\Infrastructure\DAL\Mapping\MoneyType
            s__email: App\Shared\Infrastructure\DAL\Mapping\EmailType
            s__user__user_sso_id: App\User\Infrastructure\DAL\Mapping\UserSsoIdType
            wallet__wallet_id: App\Wallet\Infrastructure\DAL\Mapping\WalletIdType
            user__cyclist_verification_process_id: App\User\Infrastructure\DAL\Mapping\CyclistVerificationProcessIdType
            user__cyclist_verification_history_collection: App\User\Infrastructure\DAL\Mapping\CyclistVerificationHistoryCollectionType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App\Shared:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/DAL/Mapping'
                prefix: 'App\Shared\Domain'
                alias: Shared
            App\User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/DAL/Mapping'
                prefix: 'App\User\Core'
                alias: User
            App\Wallet:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Wallet/Infrastructure/DAL/Mapping'
                prefix: 'App\Wallet\Domain'
                alias: Wallet
        controller_resolver:
            auto_mapping: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
