framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    default_bus: command.bus
    buses:
      query.bus: ~
      command.bus:
        middleware:
          - doctrine_transaction
      event.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
          allow_no_senders: false
        middleware:
          - doctrine_transaction

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # todo - migrate to async transport, rabbit?
      async: sync://
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    routing:
      'App\Shared\Application\Bus\Event\IModuleIntegrationEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
