services:
  php-fpm:
    build:
      context: docker/php-fpm
      target: dev
      args:
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        HOST_USER_ID: ${HOST_USER_ID}
    environment:
      PHP_IDE_CONFIG: serverName=app_server
    volumes:
      - .:/var/www/html/app
  nginx:
    build: docker/nginx
    volumes:
      - .:/var/www/html/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: app_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
