services:
  php-fpm:
    build:
      context: docker/php-fpm
      target: dev
      args:
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        HOST_USER_ID: ${HOST_USER_ID}
    environment:
      PHP_IDE_CONFIG: serverName=app_server
    volumes:
      - .:/var/www/html/app
  nginx:
    build: docker/nginx
    volumes:
      - .:/var/www/html/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"

  postgres-test:
    image: postgres:17.0
    environment:
      POSTGRES_DB: app_db_test
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5433:5432"

  redis:
    image: redis:8.0
    command: ["redis-server", "--requirepass", "password"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port", "8080"]
