<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250531123858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
            CREATE TABLE user_user (sso_id VARCHAR(36) NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, id VARCHAR(36) NOT NULL, PRIMARY KEY(id))
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F7129A807843BFA4 ON user_user (sso_id)
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F7129A80F85E0677 ON user_user (username)
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE TABLE user_user_role (user_id VARCHAR(36) NOT NULL, role VARCHAR(255) NOT NULL, PRIMARY KEY(user_id, role))
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE INDEX IDX_2D084B47A76ED395 ON user_user_role (user_id)
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE TABLE wallet_transaction (amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_type VARCHAR(255) NOT NULL, created_by_author_id VARCHAR(36) DEFAULT NULL, wallet_id VARCHAR(26) NOT NULL, PRIMARY KEY(id))
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE INDEX IDX_7DAF972712520F3 ON wallet_transaction (wallet_id)
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE TABLE wallet_wallet (user_id VARCHAR(36) NOT NULL, balance INT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id VARCHAR(26) NOT NULL, PRIMARY KEY(id))
        SQL
        );
        $this->addSql(
            <<<'SQL'
            CREATE UNIQUE INDEX UNIQ_CCC80D5BA76ED395 ON wallet_wallet (user_id)
        SQL
        );
        $this->addSql(
            <<<'SQL'
            ALTER TABLE user_user_role ADD CONSTRAINT FK_2D084B47A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL
        );
        $this->addSql(
            <<<'SQL'
            ALTER TABLE wallet_transaction ADD CONSTRAINT FK_7DAF972712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet_wallet (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
            ALTER TABLE user_user_role DROP CONSTRAINT FK_2D084B47A76ED395
        SQL
        );
        $this->addSql(
            <<<'SQL'
            ALTER TABLE wallet_transaction DROP CONSTRAINT FK_7DAF972712520F3
        SQL
        );
        $this->addSql(
            <<<'SQL'
            DROP TABLE user_user
        SQL
        );
        $this->addSql(
            <<<'SQL'
            DROP TABLE user_user_role
        SQL
        );
        $this->addSql(
            <<<'SQL'
            DROP TABLE wallet_transaction
        SQL
        );
        $this->addSql(
            <<<'SQL'
            DROP TABLE wallet_wallet
        SQL
        );
    }
}
