@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

'--- Actors & External Systems ---
Person(cyclist, "Cyclist", "Person who rents a bike")
Person(admin, "Admin", "Company worker")
System_Ext(payment, "Payment", "Third‑party payment processor")
System_Ext(sso, "SSO\nSingle Sign-On", "Authentication")
System(app, "Bikeo", "Platform for city bike rentals")

'--- Interactions ---
Rel(cyclist, app, "rents bike")
Rel(cyclist, payment, "makes payment")
Rel_L(cyclist, sso, "authenticates")
Rel_L(admin, sso, "authenticates")

Rel(admin, app, "manages bikes fleet, rentals, cyclist")
Rel(app, payment, "delegates payment")

LAYOUT_WITH_LEGEND()
@enduml
