@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(cyclist, "Cyclist")
Person(admin, "Admin")
System_Ext(payment, "Payment", "Third‑party payment processor")
System_Ext(sso, "SSO\nSingle Sign-On", "Authentication")

System_Boundary(c1, "Bikeo") {
    Container(spa, "Single Page Application", "Js, React")
    Container(api, "Bikeo API", "PHP, Symfony", "Modular Monolith")
    ContainerQueue("externalIntegrationEventQueue", "External Integration Event Queue", "Rabbit" ,"SSO events")
    ContainerDb(database, "Database", "PostgreSQL", "Modules database")
    ContainerDb(redis, "Cache", "Redis", "Doctrine cache, Lock, other...")
}

Rel_L(cyclist, sso, "Uses", "HTTPS")
Rel_L(admin, sso, "Uses", "HTTPS")
Rel(cyclist, spa, "Uses", "HTTPS")
Rel(admin, spa, "Uses", "HTTPS")
Rel(spa, api, "Uses", "HTTPS")
Rel(api, database, "Reads / Writes", "SQL")
Rel(api, redis, "Reads / Writes")
Rel(api, payment, "Delegates payment", "HTTPS")
Rel(api, externalIntegrationEventQueue, "pub / sub external integration event")
Rel(cyclist, payment, "Makes payment", "HTTPS")

LAYOUT_WITH_LEGEND()
@enduml
