restaurant__controllers:
    resource:
        path: ../src/Restaurant/Infrastructure/Api/Controller/
        namespace: App\Restaurant\Infrastructure\Api\Controller
    type: attribute

shared__controllers:
    resource:
        path: ../src/Shared/Infrastructure/Api/Controller/
        namespace: App\Shared\Infrastructure\Api\Controller
    type: attribute
